apiVersion: v1
kind: Service
metadata: 
  name: node-app-service
  namespace: node-app
spec: 
  selector: 
    app: node-app
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 3000 #container port
  # type: ClusterIP #Exposes the app internally (only accessible from within the Kubernetes cluster).
  #type: LoadBalancer Used in cloud environments like Azure Kubernetes Service (AKS) to get a public IP.
  type: LoadBalancer
